#_*_encoding:GBK*_
import time,random,sys,os
from lib.common.adbevent import adb
from lib.common.runinfo import run_log
from lib.common.logcat import log
import threading
import queue

device=' 001AAAAJC100202E5E '
path=os.path.abspath('.')
print('')
print(path)
adb=adb(device=device)
logpath=path+'/'
log=log(log_path=logpath,device=device)
logO=run_log(logging_path=path,logger='log').getlog()
num=0
adb.order('logcat -c')
log.open(module='sleep_appPlay')

thread_l = queue.Queue()

def thread_check():
    while True:
        win,jude = adb.windows('com.android.tv.settings')
        if win == True:
            adb.back()
        time.sleep(1)

def thread_log():
    log = os.popen('adb ' + device + 'logcat')
    googlepath = os.path.abspath('.') + '/'
    os.popen('adb ' + device + ' logcat -b all > ' + googlepath + 'logcat-ball.log')
    read = log.readline()
    while read:

        if thread_l.empty():
            if thread_l.get() == 'q':
                thread_l.queue.clear()
                time.sleep(2)
                break

        if "java.lang.NullPointerException: Attempt to invoke interface method \'java.lang.Object com.google.common.base.Supplier.get()\' on a null object reference" in str(read):
            os.popen('adb ' + device + ' pull /data/user_de/0/com.android.shell/files/bugreports/ ' + googlepath)
            time.sleep(3)
            os.popen('adb ' + device + 'exec-out screencap -p > ' + googlepath + 'temp.png')
            time.sleep(3)
            os.popen('adb ' + device + ' shell "getprop ro.build.display.id" > ' + googlepath + 'getprop.txt')
            time.sleep(3)
            os.popen('adb ' + device + ' shell "pm dump com.google.android.gms | grep -i version" > ' + googlepath + 'gms.txt')
            time.sleep(3)
            os.popen('adb ' + device + ' shell "pm dump com.google.android.tvlauncher | grep -i version" > ' + googlepath + 'tvlanucher.txt')
            time.sleep(3)
            os.popen('adb ' + device + ' shell "pm dump com.google.android.youtube.tv |grep -i version" > ' + googlepath + 'youtube.txt')
            time.sleep(3)
            os.popen('adb ' + device + ' shell "pm dump com.google.android.katniss |grep -i version" > ' + googlepath + 'katniss.txt')
            time.sleep(3)
            os.popen('adb ' + device + ' shell "pm dump com.google.android.inputmethod.latin |grep -i version" > ' + googlepath + 'latin.txt')
            time.sleep(3)
            os.popen('adb ' + device + ' shell "pm dump com.google.android.apps.mediashell |grep -i version" > ' + googlepath + 'mediashell.txt')
            time.sleep(3)
            os.popen('adb ' + device + 'bugreport ' + googlepath)
            time.sleep(60)
            break
        read = log.readline()

thread_thred1 = threading.Thread(target=thread_check)
thread_thred1.start()

thread_thred2 = threading.Thread(target=thread_log)
thread_thred2.start()

while True:
    num += 1
    logO.info('开始执行第' + str(num) + '次')
    logO.info('启动prime video')
    result,win = adb.app_start(times=20,package='com.amazon.amazonvideo.livingroom/com.amazon.ignition.IgnitionActivity')
    logO.info(result)
    logO.info(win)
    adb.down(3, 1)
    adb.ok(1, 10)
    adb.down(2, 3)
    adb.ok(1, 10)
    adb.down(3)
    adb.left(3)
    adb.ok(1, 10)
    for i in range(6):
        result, windows = adb.windows('com')
        logO.info(result)
        logO.info(windows)
        time.sleep(10)
    adb.oneplus(type=1)
    time.sleep(2)
    adb.ok(1,20)
    adb.oneplus()
    time.sleep(3)
    logO.info('启动YouTube')
    result,win = adb.app_start(times=20,package='com.google.android.youtube.tv')
    logO.info(result)
    logO.info(win)
    adb.right(1, 3)
    adb.ok(1, 10)
    for i in range(6):
        result, windows = adb.windows('com')
        logO.info(result)
        logO.info(windows)
        time.sleep(10)
    adb.oneplus(type=1)
    time.sleep(2)
    adb.ok(1,20)
    adb.oneplus()
    time.sleep(3)
    logO.info('启动FileBrowser')
    result,win = adb.app_start(times=3,package='com.oneplus.tv.filebrowser/.ui.activity.MainActivity')
    logO.info(result)
    logO.info(win)
    adb.ok(1, 5)
    adb.right(2)
    adb.ok(1, 10)
    for i in range(6):
        result, windows = adb.windows('com')
        logO.info(result)
        logO.info(windows)
        time.sleep(10)
    adb.oneplus(type=1)
    time.sleep(2)
    adb.ok(1,20)
    adb.oneplus()
    time.sleep(3)
    logO.info('启动Zee5')
    result,win = adb.app_start(times=25,package='com.graymatrix.did/com.zee5.splash.SplashActivity')
    logO.info(result)
    logO.info(win)
    adb.down(2, 3)
    adb.ok(2, 3)
    for i in range(7):
        result, windows = adb.windows('com')
        logO.info(result)
        logO.info(windows)
        time.sleep(10)
    adb.oneplus(type=1)
    time.sleep(2)
    adb.ok(1,20)
    adb.oneplus()
    time.sleep(3)

    # adb.oneplus(type=temp)
    # time.sleep(2)
    # adb.ok(temp, 20)
    # adb.oneplus()
    # time.sleep(3)
    logO.info('启动netflix')
    result,win = adb.app_start(times=20,package='com.netflix.ninja/.MainActivity')
    logO.info(result)
    logO.info(win)
    adb.ok(1, 5)
    adb.down(2, 3)
    adb.ok(2, 5)
    adb.ok(1, 10)
    for i in range(7):
        result, windows = adb.windows('com')
        logO.info(result)
        logO.info(windows)
        time.sleep(10)
    adb.oneplus(type=1)
    time.sleep(2)
    adb.ok(1,20)
    adb.oneplus()
    logO.info('启动Live TV')
    result,win = adb.app_start(times=3,package='com.oneplus.tv.android.livetv/.ActivityEntrance')
    logO.info(result)
    logO.info(win)
    if num==1:
        adb.back(1,2)
        adb.menu()
        time.sleep(3)
        adb.left(10)
        time.sleep(1)
        adb.ok(2,3)
        result,window=adb.windows('livetv')
        if result==True:
            pass
        else:
            adb.home()
            time.sleep(2)
            adb.app_start(package='com.oneplus.tv.android.livetv/.ActivityEntrance')
            time.sleep(3)
            adb.menu()
            time.sleep(3)
            adb.left(10)
            time.sleep(1)
            adb.ok(2, 3)
    else:
        pass
    for i in range(7):
        result, windows = adb.windows('com')
        logO.info(result)
        logO.info(windows)
        time.sleep(10)
    adb.oneplus(type=1)
    time.sleep(2)
    adb.ok(1, 20)
    adb.oneplus()
    time.sleep(3)
    logO.info('启动JioCinema')
    result,win = adb.app_start(times=15,package='com.jio.media.stb.ondemand/com.jio.media.stb.jioondemand.ui.splash.SplashActivity')
    logO.info(result)
    logO.info(win)
    adb.left(3)
    adb.up(3,1)
    adb.down(1,2)
    adb.ok(1,5)
    adb.up(3)
    time.sleep(1)
    adb.down(1,2)
    adb.ok(1,5)
    for i in range(7):
        result, windows = adb.windows('com')
        logO.info(result)
        logO.info(windows)
        time.sleep(10)
    adb.oneplus(type=1)
    time.sleep(2)
    adb.ok(1, 20)
    adb.oneplus()
    time.sleep(3)
    logO.info('启动E-Manual')
    result,win = adb.app_start(times=3,package='com.oneplus.tv.userguide/.MainActivity')  # E-Manual
    logO.info(result)
    logO.info(win)
    adb.right()
    time.sleep(2)
    adb.ok()
    for i in range(3):
        result, windows = adb.windows('com')
        logO.info(result)
        logO.info(windows)
        time.sleep(10)
    adb.oneplus(type=1)
    time.sleep(2)
    adb.ok(1, 20)
    adb.oneplus()
    time.sleep(3)
    result,win = adb.app_start(times=15,package='in.startv.hotstar/.ui.splash.TVSplashActivity')  # HotStar
    logO.info(result)
    logO.info(win)
    adb.left(3)
    time.sleep(1)
    adb.up(3)
    time.sleep(1)
    adb.down(2,2)
    adb.ok(2,5)
    for i in range(7):
        result, windows = adb.windows('com')
        logO.info(result)
        logO.info(windows)
        time.sleep(10)
    adb.oneplus(type=1)
    time.sleep(2)
    adb.ok(1, 20)
    adb.oneplus()
    time.sleep(3)
    logO.info('启动Oxygen')
    adb.oneplus()
    time.sleep(3)
    adb.down(2,2)
    adb.ok()
    for i in range(7):
        result, windows = adb.windows('com')
        logO.info(result)
        logO.info(windows)
        time.sleep(10)
    adb.oneplus(type=1)
    time.sleep(2)
    adb.ok(1, 20)
    adb.oneplus()
    time.sleep(3)

    thread_l.put('q')
    time.sleep(5)
    thread_thred2 = threading.Thread(target=thread_log)
    thread_thred2.start()
    time.sleep(5)

    logO.info('已执行完第' + str(num) + '次')
    time.sleep(3)